# **DAY-2**
**(NUMPY LIBRARY)**

In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3,4,5,6,7])

b= np.array([2,4,6,8,10,12,14])

print(a)
print(b)

[1 2 3 4 5 6 7]
[ 2  4  6  8 10 12 14]


In [ ]:
# 2-D Array

m= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(a.shape)
print(m.shape)
print(a.dtype)
print(m.dtype)
print(m.ndim)


(7,)
(3, 3)
int64
int64
2


In [ ]:
np.zeros(5)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,3)

array([[0.61817802, 0.1047955 , 0.33780478],
       [0.51893879, 0.46488253, 0.99675391],
       [0.41343015, 0.99407428, 0.58053994]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#1-D Array Indexing

In [ ]:
u= np.array([10,20,30,40,50])
u[0]

np.int64(10)

In [ ]:
u[-1]

np.int64(50)

In [ ]:
u[1:4]

array([20, 30, 40])

In [ ]:
u[::2]

array([10, 30, 50])

#2-D Array Indexing

In [ ]:
x= np.arange(1,10).reshape(3,3)

print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x[0,1]

np.int64(2)

In [ ]:
x[1:, 2:]

array([[6],
       [9]])

In [ ]:
x[:, 1]

array([2, 5, 8])

In [ ]:
u[u>35]

array([40, 50])

In [ ]:
u[np.array([0,2,4])]

array([10, 30, 50])

# Broadcasting

In [ ]:
k= np.arange(6).reshape(2,3)
print(k)
print()

l=np.array([100,200,300])
print(l)
sum=k+l
print()
print(sum)

[[0 1 2]
 [3 4 5]]

[100 200 300]

[[100 201 302]
 [103 204 305]]


In [ ]:
k= np.arange(6).reshape(2,3)
print(k)
print()

l=np.array([100,200,300])
print(l)
sum=k-l
print()
print(sum)

[[0 1 2]
 [3 4 5]]

[100 200 300]

[[-100 -199 -298]
 [ -97 -196 -295]]
